---
- name: get current networks
  virt_net:
    command: list_nets
  register: networks

- name: stop and remove the default network
  virt_net:
    name: default
    command: "{{ item }}"
  with_items:
    - destroy
    - undefine
  when: "'default' in networks.list_nets"

- name: add the new default network definition
  virt_net:
    name: default
    command: define
    xml: "{{ lookup('template', 'templates/default.xml.j2') }}"

- name: start the default network
  virt_net:
    name: default
    command: start
    autostart: yes

- name: stop and remove the default2 network
  virt_net:
    name: default2
    command: "{{ item }}"
  with_items:
    - destroy
    - undefine
  when: "'default2' in networks.list_nets"

- name: add the new default2 network definition
  virt_net:
    name: default2
    command: define
    xml: "{{ lookup('template', 'templates/default2.xml.j2') }}"

- name: start the default2 network
  virt_net:
    name: default2
    command: start
    autostart: yes


